### ISSUE TITLE
Some automap options don't seem to work properly + core options not applied on launch + disable pause on intro screens and menus?

### ISSUE THREAD

**Issue by bslenul** [libretro/ecwolf#18]
Hey, sorry if it's a bit soon to report bugs since it's a WIP core, but I didn't see any mention of these in the "Known glitches" [in the news post](https://www.libretro.com/index.php/ecwolf-wolfenstein-3d-libretro-core-wip-available-today-on-windowsmaclinuxandroid/).

* **Show map as overlay:** "On" and "Off" work fine, "On + Normal" only shows overlay, it supposed to show overlay then on a 2nd press the normal automap.
* **Textured floors in automap:** doesn't work, floor is still the same grey as when the option is "Off".
* **Textured Overlay in automap:** doesn't work, walls are still green.
* **Pause game in automap:** "Off" doesn't work, you can't move the normal map and you can't move the character while overlay map is open.
* Not a glitch but I think Pause button should act as Fire button during the intro screens and menus.

**edit:** also it looks like core options are not applied on startup, you have to switch an option (doesn't seem to matter which one) before they're applied. e.g. if you have "Always run" set to ON, when you start the game the character will not run until you switch any core options, same with "Screen size", etc.

**edit2:** maybe not every core options, resolution and framerate options seem to stick for example.

Tested on both Windows 10 and a Linux VM, latest core and RA nightlies.

**Comment by phcoder** [comment]
Please retest. Should be fixed now

**Comment by bslenul** [comment]
Thanks for the update! 👍 

* Core options are applied on startup ✔️ 
* Texture options for automap and overlay work ✔️ 
* "Pause game in automap" works fine, but I misunderstood that one previously, it only affects automap, NOT overlay, so that was intended ✔️   
(That option should probably be "ON" by default btw :p)
* "Show map as overlay On + Normal" is still only showing overlay instead of cycling from automap to overlay ❌ 
* Still can't move while automap (+ pause option to OFF) or overlay is opened ❌
