### ISSUE TITLE
ECWolf crashes console (Nintendo Switch running Atmosphere CFW)

### ISSUE THREAD

**Issue by ShadowOne333** [libretro/ecwolf#46]
Upon trying to load a vanilla release of Wolfenstein 3D by selecting the ECWolf core, and then the Wolf3D.exe executable with all of Wolf3D's files in the same folder through RetroArch in a hacked Nintendo Switch, the console's custom firmware (Atmosphere) crashes and forces a reboot of the console.

A similar result occurs when trying to load Spear of Destiny through it (spear.exe/wolf3D.exe)
The same thing happens with both the DOS and GOG releases of both games.

The only version which seems to boot fine is the shareware release of Wolfenstein 3D, grabbed from the buildbot.

The ECWolf.pk3 is located inside /retroarch/cores/system, and also (to be sure) it is also located within the same folder as each game (Wolf3D/SoD).

**Comment by phcoder** [comment]
Did you put ecwolf.pk3 in the BIOS directory?

**Comment by ShadowOne333** [comment]
Yes, I included said file inside the "system" folder where all the BIOS files are, and just to be sure, I included said pk3 file alongside the .exe for each game (Wolfenstein 3D/Spear of Destiny).

They both refuse to work, while only the shareware version seems to run.

**Comment by Shaneus2k2** [comment]
For what it's worth, I also have a crashing issue with it on Vita (as well as Switch). Does work on the Win64 build though.

Edit: Never mind, didn't realise the ecwolf.pk3 file didn't download to the system folder automatically, works on Vita now (at least, the shareware does).

**Comment by inactive123** [comment]
@Shaneus2k2 Does it work for you on Switch now?

**Comment by ShadowOne333** [comment]
@twinaphex I have a build from some days ago on my Switch, and can confirm it works now.
I'm running both full Wolf3D and Spear of Destiny through ECWolf, and shareware as well.

Now if only the options and save menu worked... :p

**Comment by inactive123** [comment]
HI, you can open up a separate issue for this. We can consider this one closed then.
