### ISSUE TITLE
Missing libretro.h

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/ecwolf#63]
UILD/ecwolf-master/src/libretro/libretro_core_options.h:7:22: fatal error: libretro.h: No such file or directory
Build error.

**Comment by inactive123** [comment]
Should not be an easy at least in master. Reopen if you still experience issues.

**Comment by mantheman** [comment]
/ecwolf/src/libretro/libretro_core_options.h:7:10: fatal error: libretro.h: No such file or directory
For me it builds fine up until this pint:
https://github.com/libretro/ecwolf/commit/8ffecaaaf8afe83bb0262fb83cf26abe8af9405f

**Comment by christianhaitian** [comment]
Just open src/libretro/libretro_core_options.h and on line 7, change `<libretro.h>` to `"libretro.h"` and it should build successfully.  I've submitted a pull request so this fix will hopefully be included.

**Comment by Zombie-Ryushu** [comment]
Understood. Thank you.
