### ISSUE TITLE
ECWolf Mods

### ISSUE THREAD

**Issue by vahacris** [libretro/ecwolf#70]
Can ECWolf mods can be played somehow with ecwolf libretro core?

**Comment by phcoder** [comment]
Yes, choose "Subsystem" > "Load with 2 packs"

**Comment by vahacris** [comment]
I understand that after choosing that option i should choose mod pk3 file?

I try that but the game still give me only 6 standard episode to choose.

śr., 26 sty 2022, 13:06 użytkownik Vladimir Serbinenko <
***@***.***> napisał:

**Comment by vahacris** [comment]
> Yes, choose "Subsystem" > "Load with 2 packs"

I understand that after choosing that option i should choose mod pk3 file?

I try that but the game still give me only 6 standard episode to choose.

**Comment by phcoder** [comment]
Please provide more details as to which packs and mods you attempted (but don't post any links to pirated materials). Also feel free to reach me by e-mail

**Comment by vahacris** [comment]
I give up and just used mods with modified exe. I link to modified exe in playlist and everything is good.
