### ISSUE TITLE
[PS2] Color palette is broken

### ISSUE THREAD

**Issue by hugorsgarcia** [libretro/ecwolf#77]
Color palette is broken on Playstation 2 you almost can't see anything on screen. There also some random crashes

**Comment by phcoder** [comment]
Nailed both of them. Color issue is due to PS2 using another pixel format. Random crashes come from adlib somehow. I made patches to fix color and disable adlib. Will commit and then I need you to retest

**Comment by phcoder** [comment]
Can you try https://git.libretro.com/phcoder/ecwolf/-/jobs/1765224/artifacts/browse ?

**Comment by phcoder** [comment]
I went ahead and merged my changes

**Comment by hugorsgarcia** [comment]
The color palete has been fix. But the game still crashes after you select the difficulty. Are you testing on a real PS2 or on an emulator?

**Comment by phcoder** [comment]
> The color palete has been fix. But the game still crashes after you select the difficulty. Are you testing on a real PS2 or on an emulator?

Real PS2. Which version are you testing? Can you reset the config?

**Comment by phcoder** [comment]
Also: please file one bug per issue.

**Comment by hugorsgarcia** [comment]
Yeap. Even after a cleaning all configs and copying all over again from scratch still crashes into a black void. I am using the latest nightly build

**Comment by hugorsgarcia** [comment]
These are all my Wolfenstein files, there is also ecwolf.pk3 inside system folder as it should. I know all my files are correct because DosBox can play it just fine

AUDIOHED.WL6                                                         
AUDIOT.WL6                                                           
CONFIG.WL6                                                           
ecwolf.pk3                                                           
GAMEMAPS.WL6                                                         
LAUNCH.BAT                                                           
MAPHEAD.WL6                                                          
VGADICT.WL6                                                          
VGAGRAPH.WL6                                                         
VGAHEAD.WL6                                                          
VSWAP.WL6                                                            
WOLF3D.EXE

**Comment by phcoder** [comment]
Please:
a) make a separate bug for the remaining separate issue
b) specify what "latest" mean (i.a. date and hash)
c) I need hashes of involved files and which file you open
